FROM python:3.7-slim

WORKDIR /app

COPY requirements.txt .env /app/

RUN cd /app/ && \
pip install -r requirements.txt && \
pip uninstall -y protobuf && \
pip install protobuf==3.20.3

COPY test.py /app/

COPY ./telemanom/ /app/telemanom/

EXPOSE 8000

CMD ["uvicorn", "test:app", "--host", "0.0.0.0", "--port", "8000"]
