FROM python:3.7-slim

RUN pip install --no-cache-dir \
    mlflow==1.30.1 \
    psycopg2-binary \
    boto3 \
    pymysql

EXPOSE 5000

ENTRYPOINT ["mlflow"]

CMD ["server", "--backend-store-uri=postgresql://mlflow:mlflow@postgres:5432/mlflow", "--default-artifact-root=s3://mlflow", "--host=0.0.0.0", "--port=5000"]